server:
  port: 9002
  tomcat:
    uri-encoding: UTF-8

thymeleaf:
  cache: false
  mode: LEGACYHTML5

logging:
  level:
    com:
      bjyx: debug

spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/bjyxquery?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
#      password: GuoruiJUN@07
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

perMoney: 0.5

#°æ±¾ºÅ
version: 1.01

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

